name: Update Homepage

on:
  repository_dispatch:
    types: [trigger-c-build]  # 监听来自 UpdateHomepage-Build 仓库的 trigger-c-build 事件

jobs:
  check-update-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出 UpdateHomepage 仓库
      - name: Checkout UpdateHomepage repository
        uses: actions/checkout@v2
        with:
          repository: Joker2184/UpdateHomepage
          token: ${{ secrets.PAT_TOKEN }}  # 使用 PAT_TOKEN 进行授权
          path: updatehomepage

      # 2. 运行 VersionJson.py 脚本生成内容
      - name: Run VersionJson.py to generate content
        run: |
          python updatehomepage/VersionJson.py  # 执行生成内容的 Python 脚本

      # 3. 删除 UpdateHomepage 仓库中已存在的旧文件
      - name: Delete old files from UpdateHomepage repository
        run: |
          rm -f updatehomepage/UpdateHomepage.xaml.ini
          rm -f updatehomepage/UpdateHomepage.json
        # 删除目标仓库中的旧文件（如果存在）

      # 4. 将生成的文件复制到 UpdateHomepage 仓库
      - name: Copy generated content to UpdateHomepage repository
        run: |
          cp -r updatehomepage/generated/* updatehomepage/
        # 将生成的文件复制到目标仓库

      # 5. 提交并推送更新到 UpdateHomepage 仓库
      - name: Commit and push changes to UpdateHomepage repository
        run: |
          cd updatehomepage
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update homepage content"
          git push origin main
        # 提交并推送更新到目标仓库
